---
include:
- "**/*.rb"
exclude:
require: []
domains: []
reporters:
- all!
formatter:
  rubocop:
    cops: safe
    except: []
    only: []
    extra_args: []
require_paths: []
plugins: []
max_files: 5000
